#!/bin/bash

set -e    # halt on first error

# use 'g++' as the compiler
CPP=g++

# be aggressive about warnings and errors, optimization level 3
FLAGS="-g -O3 -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -pedantic"


# clear out old object files
rm -f *.o

# compile
$CPP $FLAGS -o language language.cpp main.cpp
