#!/bin/bash

set -e    # halt on first error

# use 'clang++' as the compiler
CPP=clang++

# be aggressive about warnings and errors, optimization level 3
FLAGS="-O3 -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -pedantic"


# clear out old object files
rm -f *.o

# compile
$CPP $FLAGS -o frequencies language.cpp main.cpp
